services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-test
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  cassandra-init:
    image: cassandra:4.1
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./tests/docker/init.cql:/init.cql:ro
    command: >
      bash -c "
        echo 'Waiting for Cassandra to be ready...' &&
        until cqlsh cassandra -f /init.cql; do
          echo 'Cassandra not ready yet, waiting 5 seconds...'
          sleep 5
        done &&
        echo 'Cassandra initialized successfully'
      "

volumes:
  cassandra_data: 
